get data from hatcheries
AustinRS016/Salmon-Finder-Version-2 pull request #6
Opened 2023-04-19 22:30 UTC by AustinRS016

2023-04-20 02:08 UTC, purplexionist commented on .gitignore
> +
nit: new line

2023-04-20 02:09 UTC, purplexionist commented on python/getHatcheryData.py
> +results = client.get("9q4e-xhag", limit=1000)
https://dev.socrata.com/docs/queries/select.html

We probably should just use this if the API provides it

2023-04-23 00:51 UTC, purplexionist commented on python/config.py
> +    WA_HATCHERY_DATA = auto()
nice job

2023-04-23 00:51 UTC, purplexionist commented on python/config.py
> +
nit: new line

2023-04-23 00:51 UTC, purplexionist commented on python/getHatcheryData.py
> +
nit: extra line again

2023-04-23 00:52 UTC, purplexionist commented on python/getHatcheryData.py
> +prin
nit: i think this is left overs

2023-04-23 00:54 UTC, purplexionist approved these changes
LGTM with a few nits and some leftovers

2023-04-23 00:55 UTC, purplexionist commented on python/config.py
> +    WA_HATCHERY_DATA = auto()
Oh wait, you aren't using your enum in the data

2023-04-23 00:56 UTC, purplexionist commented on python/config.py
> +hathceries = {'BAKER LAKE HATCHERY': ('WA_HATCHERY_DATA',), 'BEAVER CREEK HATCHERY': ('WA_HATCHERY_DATA',), 'BINGHAM CREEK HATCHERY': ('WA_HATCHERY_DATA',),
hathceries = {'BAKER LAKE HATCHERY': (Hatcheries.WA_HATCHERY_DATA,), 

Might have to define class Hatcheries above this

2023-04-23 00:56 UTC, purplexionist requested changes
You should use the enum in the data

2023-04-23 17:07 UTC, AustinRS016 commented
My autoformatter has been adding these new lines.. Once you get a linter set up I'll turn it off.

2023-04-23 17:08 UTC, merged